services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  jenkins_ansible:
    container_name: jenkins_ansible
    image: jenkins_ansible
    build:
      context: jenkins_ansible
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - $PWD/jenkins_ansible_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: remote-host
    build:
      context: centos7
    volumes:
      - $PWD/sql-aws-s3-backup.sh:/tmp/script.sh
    networks:
      - net
  db_host:
     container_name: db
     image: mysql:5.7
     environment:
       - "MYSQL_ROOT_PASSWORD=1234"
     volumes:
       - "$PWD/db_data:/var/lib/mysql"
     networks:
       - net
  web:
     container_name: web
     image: ansible-web
     build:
       context: jenkins_ansible/web
     ports:
       - "80:80"
     networks:
       - net
  git-server:
    image: gitlab/gitlab-ce:latest
    container_name: git-server
    hostname: 'gitlab.example.com'
    ports:
      - '8090:80'
      - '8443:443'
      - '2422:22'
    volumes:
      - './gitlab_home/config:/etc/gitlab'
      - './gitlab_home/logs:/var/log/gitlab'
      - './gitlab_home/data:/var/opt/gitlab'
    networks:
      - net
  jenkins_docker:
    container_name: jenkins_docker
    image: jenkins/docker
    build:
      context: pipeline
    ports:
      - "8082:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net:
